### ISSUE TITLE
Add support for cowbells?

### ISSUE THREAD

**Issue by Qix-** [sindresorhus/cows#1]
There needs to be more cowbell. Maybe in V1?

![Cowbell](https://upload.wikimedia.org/wikipedia/en/f/fc/Walken-Cowbell.jpg)

**Comment by sindresorhus** [comment]
![image](https://cloud.githubusercontent.com/assets/170270/13090998/a9cdd6b0-d52b-11e5-83ec-614143c9a3bb.png)

**Comment by dthree** [comment]
![cows](https://cloud.githubusercontent.com/assets/10319897/13097288/84e476a8-d4d4-11e5-9b79-1219ea92dfa7.jpg)

**Comment by sindresorhus** [comment]
Here you go:

- https://github.com/sindresorhus/cows/blob/addb91e78083818a5dce79e22d7ed3aea73c902e/cows.txt#L1934-L1944
- https://github.com/sindresorhus/cows/blob/addb91e78083818a5dce79e22d7ed3aea73c902e/cows.txt#L2902-L2915
- https://github.com/sindresorhus/cows/blob/addb91e78083818a5dce79e22d7ed3aea73c902e/cows.txt#L4284-L4301

**Comment by Qix-** [comment]
u r god ov cow thx
