### ISSUE TITLE
Relabel Teenage Mutant Ninja Cows?

### ISSUE THREAD

**Issue by hackingoff** [sindresorhus/cows#5]
```
         (__)               (__)  |    |  (__)
         (--)               (--)  |    |  (--)
  /-------\/   /o    /-------\/   |    I   \/-------\
 / |  L  |----< o   / |  D  |----<T    I>----|  M  | \
*  ||----|   /  o  *  ||----|     I    I     |----||  *
   ^^    ^      |     ^^    ^          |     ^    ^^
                |                      |
              Teenage Mutant Ninja Cows
```
Current cow labeling order: L, D, M.

Leftmost appears to have nunchaku, middle a sword, and right a bo staff. Mapping them to their turtle counterparts, they'd they'd be ~~Michaelangelo~~ Moochaelangelo, ~~Leonardo~~ Longhornardo, and ~~Donatello~~ Dairytello.

Proposed cow labeling order: M, L, D.

**Comment by passy** [comment]
Amazing.

**Comment by samccone** [comment]
Ace spot +1

**Comment by addyosmani** [comment]
:heart_eyes:

**Comment by hackebrot** [comment]
:cow:

**Comment by blesh** [comment]
:+1: +1 I need this.

**Comment by A** [comment]
I faced with same issue! Thank you for the fix!

**Comment by wayneashleyberry** [comment]
:sparkles:

**Comment by NickHeiner** [comment]
:+1: yes, I also repro'd this issue on Mac OSX. Fixing this would definitely help my team a lot. Thanks!
